# For creating php server and copying file from the local volume to docker
# FROM php:7.0-apache
# COPY h:/docker/testapp /var/www/html
# EXPOSE 80

FROM ubuntu
RUN apt-get update -y && apt-get install -y curl 
RUN apt install -y vim
RUN mkdir /jayfolder
# CMD ["curl", "wttr.in/Chicago"]


# web:
#   build: .
#   ports:
#    - "5000:5000"
#     links:
#    - redis
# redis:
#   image: redis